// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wealth_manager.Api.Data;
using wealth_manager.Api.Models;

#nullable disable

namespace wealth_manager.Api.Data.Migrations;

[DbContext(typeof(WealthManagerDbContext))]
partial class WealthManagerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("wealth_manager.Api.Models.GoldAsset", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<decimal>("Grams")
                .HasColumnType("numeric(18,4)")
                .HasColumnName("Grams");

            b.Property<GoldKarat>("Karat")
                .HasConversion<int>()
                .HasColumnType("integer")
                .HasColumnName("Karat");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("createdAt");

            b.Property<DateTime>("ModifiedAt")
                .HasDefaultValueSql("now()")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("modifiedAt");

            b.HasKey("Id");

            b.ToTable("GoldAsset", (string)null);
        });
#pragma warning restore 612, 618
    }
}
