using Microsoft.EntityFrameworkCore;
using wealth_manager.Api.Models;

namespace wealth_manager.Api.Data;

/// <summary>
/// Entity Framework Core database context for the wealth_manager database.
/// Provides access to gold assets and applies Code First configuration.
/// </summary>
public class WealthManagerDbContext(DbContextOptions<WealthManagerDbContext> options) : DbContext(options)
{
    /// <summary>Gold assets in the database.</summary>
    public DbSet<GoldAsset> GoldAssets { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<GoldAsset>(entity =>
        {
            entity.ToTable("GoldAsset");
            
            entity.HasKey(e => e.Id);
            
            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();
            
            entity.Property(e => e.Value)
                .HasColumnName("Value")
                .HasColumnType("decimal(18,2)")
                .IsRequired();
            
            entity.Property(e => e.Karat)
                .HasColumnName("Karat")
                .HasConversion<int>()
                .IsRequired();
            
            entity.Property(e => e.CreatedAt)
                .HasColumnName("createdAt")
                .HasColumnType("timestamp with time zone")
                .IsRequired();
            
            entity.Property(e => e.ModifiedAt)
                .HasColumnName("modifiedAt")
                .HasColumnType("timestamp with time zone")
                .HasDefaultValueSql("now()")
                .ValueGeneratedOnAdd()
                .IsRequired();
        });
    }

    /// <summary>Saves all changes and applies timestamp rules (CreatedAt, ModifiedAt).</summary>
    /// <returns>The number of state entries written to the database.</returns>
    public override int SaveChanges()
    {
        SetTimestamps();
        return base.SaveChanges();
    }

    /// <summary>Asynchronously saves all changes and applies timestamp rules (CreatedAt, ModifiedAt).</summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The number of state entries written to the database.</returns>
    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        SetTimestamps();
        return base.SaveChangesAsync(cancellationToken);
    }

    /// <summary>Set CreatedAt and ModifiedAt (Id is generated by the database).</summary>
    private void SetTimestamps()
    {
        var now = DateTime.UtcNow;
        foreach (var entry in ChangeTracker.Entries<GoldAsset>())
        {
            if (entry.State == EntityState.Added)
                entry.Property(e => e.CreatedAt).CurrentValue = now;
        }
    }
}
